logging:
  level:
    org:
      springframework: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hof_2
    username: root
    password: TestPass123?
  jpa:
    hibernate:
      ddl-auto: create
